on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to deploy'
        required: true
        default: 'main'
      deployment-environment:
        description: 'Select GitHub Environment for approval'
        required: true
        type: choice
        default: 'app1-test'
        options:
          - app1-test
          - app1-prod
          - app2-test
          - app2-prod
      promote-to-production:
        description: 'Deploy to Production slot? (true/false)'
        required: false
        default: 'false'

jobs:
  deploy-app1:
    uses: KrishnaPisupati05/reusable-workflow/.github/workflows/Reusable-workflow.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.deployment-environment }}
      app-name: app1
      node-version: 18.x
      app-location: app1/frontend
      output-location: build
      promote-to-production: ${{ github.event.inputs.promote-to-production }}
    secrets: inherit
