name: Call reusable workflow

on:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write   # Allow creating issues

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      app-name: app-1
      environment: prod
