name: Deploy App1

on:
  push:
    branches:
      - main
      - master
      - staging
      - dev
  workflow_dispatch:

jobs:
  deploy:
    uses: flysastech/reusable-workflows/.github/workflows/deploy.yml@main
    with:
      # Optional: only needed for production approval
      # app_name: myapp
