name: Deploy App1

on:
  workflow_dispatch:

jobs:
  deploy-app1:
    uses: ./.github/workflows/reusable-staticwebapp.yml
    with:
      app-name: app1
      environment: app1-test   # Approval environment set in GitHub
      node-version: 18.x
      app-location: frontend
      output-location: build
