name: Test Static Web App Deployment

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to test'
        required: true
        default: dev

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      app-name: app1
      environment: app1-test  # Environment configured with approvers
      working-directory: ./dummy
      app-location: dummy-app
      output-location: dummy-build
