name: Validate, Build & Deploy Static Web App

on:
  workflow_call:
    inputs:
      # Optional: app name, required only for production deployment
      app_name:
        required: false
        type: string

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Echo validation
        run: |
          echo "Validating application..."
          echo "Simulated: npm install, lint, test"

  build-and-deploy:
    name: Build & Deploy
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set deployment slot
        id: slot
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]] || \
             [[ "${GITHUB_REF}" == "refs/heads/master" ]] || \
             [[ "${GITHUB_REF}" == "refs/heads/production" ]] || \
             [[ "${GITHUB_EVENT_NAME}" == "workflow_dispatch" ]]; then
            echo "slot=production" >> $GITHUB_OUTPUT
            echo "protected=true" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/staging" ]]; then
            echo "slot=staging" >> $GITHUB_OUTPUT
            echo "protected=false" >> $GITHUB_OUTPUT
          else
            echo "slot=dev" >> $GITHUB_OUTPUT
            echo "protected=false" >> $GITHUB_OUTPUT

      - name: Preview Deployment Slot
        run: |
          echo "----------------------------------------"
          echo "Branch: ${GITHUB_REF##*/}"
          echo "Event: ${GITHUB_EVENT_NAME}"
          echo "Deployment slot: ${{ steps.slot.outputs.slot }}"
          if [[ "${{ steps.slot.outputs.protected }}" == "true" ]]; then
            echo "⚠️ Production deployment: approval required!"
          else
            echo "✅ Deployment will proceed automatically (no approval required)."
          fi
          echo "----------------------------------------"

      - name: Approval for production
        if: steps.slot.outputs.protected == 'true'
        environment: ${{ inputs.app_name }}-prod
        run: echo "Approval received. Proceeding with production deployment..."

      - name: Build App
        run: |
          echo "Building app for slot ${{ steps.slot.outputs.slot }}..."
          echo "Simulated: npm run build"

      - name: Deploy App
        run: |
          echo "Deploying app to slot ${{ steps.slot.outputs.slot }}..."
          echo "Simulated: Azure Static Web Apps deploy"
