name: Reusable Static Web App Deployment (Test Mode)

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:

  validate:
    name: Validate Build (Test Mode)
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Build
        run: |
          APP_NAME="${{ inputs.app-name }}"
          echo "Validate job: simulating build for $APP_NAME"

  approve:
    name: Await Approval (Test Mode)
    needs: validate
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Approval required from reviewers configured in environment: ${{ inputs.environment }}"

  deploy:
    name: Deploy Static Web App (Test Mode)
    needs: [validate, approve]
    runs-on: ubuntu-latest
    steps:
      - name: Determine Slot
        id: slot
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" ]]; then
            echo "slot=production" >> $GITHUB_OUTPUT
          else
            echo "slot=staging" >> $GITHUB_OUTPUT

      - name: Echo Slot Name
        run: |
          echo "Deploying to slot: ${{ steps.slot.outputs.slot }}"

      - name: Simulate Deployment
        run: |
          APP_NAME="${{ inputs.app-name }}"
          echo "Simulating deployment of $APP_NAME to slot ${{ steps.slot.outputs.slot }}"
