name: Reusable SWA Test Workflow

on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      environment:
        required: false
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Validate app
        run: |
          echo "Validating ${{ inputs.app-name }}"
          echo "Running basic tests..."
          echo "npm install && npm test (simulated)"

  await-approval:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Determine approver
        id: approver
        run: |
          # Map app-name to approver secret
          if [ "${{ inputs.app-name }}" == "app-1" ]; then
            echo "approver=${{ secrets.TEST_APPROVER_1 }}" >> $GITHUB_OUTPUT
          elif [ "${{ inputs.app-name }}" == "app-2" ]; then
            echo "approver=${{ secrets.TEST_APPROVER_2 }}" >> $GITHUB_OUTPUT
          else
            echo "approver=${{ secrets.DEFAULT_APPROVER }}" >> $GITHUB_OUTPUT
          fi

      - name: Await approval
        uses: trstringer/manual-approval@v1
        with:
          approvers: KrishnaPisupati05
          minimum-approvals: 1
          secret: manual-approval-token       # required by the action
          secret: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          issue-title: "Approval required for ${{ inputs.app-name }}"
          issue-body: "Please approve this workflow to continue testing."

  build:
    runs-on: ubuntu-latest
    needs: await-approval
    steps:
      - name: Build app
        run: |
          echo "Building ${{ inputs.app-name }}..."
          echo "npm run build (simulated)"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: ${{ inputs.environment }}
    steps:
      - name: Deploy step (simulated)
        run: echo "Deploying ${{ inputs.app-name }} to ${{ inputs.environment || 'no environment specified' }}"
